<?php
/**
 * @author Rhuan Carlos Batista <rhcarlosweb@gmail.com>
 * @version: 0.0.1-alpha
 */

defined( 'ABSPATH' ) || exit;

if ( !class_exists( 'acf_field_icomoon_select' ) ) :
    class acf_field_icomoon_select extends acf_field {
        /**
         * acf_field_icomoon_select constructor.
         *
         * This function will setup the field type data
         *
         * @param $settings
         *
         * @since 0.0.1-alpha
         */
        public function __construct( $settings ) {
            /**
             * name (string) single word
             */
            $this->name = 'icomoon_select';

            /**
             * label (string) multiple words, visible when selecting a field type
             */
            $this->label = __( 'IcoMoon', 'rhicomoon' );

            /**
             * category
             */
            $this->category = 'content';

            /**
             * settings (array) store plugin settings (url, path, version) as a reference for later use with assets
             */
            $this->settings = $settings;

            # call acf_field class will initialize the field type
            parent::__construct();
        }

        /**
         * render_field_settings
         *
         * Create extra settings for your field. These are visible when editing the field
         *
         * @param $field
         *
         * @since 0.0.1-alpha
         */
        function render_field_settings( $field ) {
            /**
             * URL selection.json file generated by IcoMoon App
             */
            acf_render_field_setting( $field, [
                'label'        => __( 'URL JSON file', 'rhicomoon' ),
                'instructions' => __( 'Insert URL of the JSON file (selection.json) to generate list of icons' ),
                'type'         => 'url',
                'name'         => 'json_url'
            ] );
        }

        /**
         * render_field
         *
         * Create the HTML interface for field
         *
         * @param $field
         *
         * @since 0.0.1-alpha
         *
         */
        function render_field( $field ) {
            // echo '<pre>';
            // print_r( $field );
            // echo '</pre>'; ?>
            <select name="<?php echo esc_attr( $field[ 'name' ] ); ?>" id="<?php echo esc_attr( $field[ 'id' ] ); ?>"></select>
        <?php }

        /**
         * input_admin_enqueue_script
         *
         * @since 0.0.1-alpha
         */
        function input_admin_enqueue_scripts() {
            $url     = $this->settings[ 'url' ];
            $version = $this->settings[ 'version' ];
        }
    }

    # call class
    new acf_field_icomoon_select( $this->settings );
endif;