<?php
/**
 * @author Rhuan Carlos Batista <rhcarlosweb@gmail.com>
 * @version: 0.0.1-alpha
 */

defined( 'ABSPATH' ) || exit;

if ( !class_exists( 'acf_field_icomoon_select' ) ) :
    class acf_field_icomoon_select extends acf_field {
        /**
         * acf_field_icomoon_select constructor.
         *
         * This function will setup the field type data
         *
         * @param $settings
         *
         * @since 0.0.1-alpha
         */
        public function __construct( $settings ) {
            /**
             * name (string) single word
             */
            $this->name = 'icomoon_select';

            /**
             * label (string) multiple words, visible when selecting a field type
             */
            $this->label = __( 'IcoMoon', 'rhicomoon' );

            /**
             * category
             */
            $this->category = 'content';

            /**
             * settings (array) store plugin settings (url, path, version) as a reference for later use with assets
             */
            $this->settings = $settings;

            # call acf_field class will initialize the field type
            parent::__construct();
        }

        /**
         * render_field_settings
         *
         * Create extra settings for your field. These are visible when editing the field
         *
         * @param $field
         *
         * @since 0.0.1-alpha
         */
        function render_field_settings( $field ) {
            /**
             * URL selection.json file generated by IcoMoon App
             */
            acf_render_field_setting( $field, [
                'label'        => __( 'URL JSON file', 'rhicomoon' ),
                'instructions' => __( 'Insert URL of the JSON file (selection.json) to generate list of icons' ),
                'type'         => 'url',
                'name'         => 'json_url'
            ] );
        }

        /**
         * render_field
         *
         * Create the HTML interface for field
         *
         * @param $field
         *
         * @since 0.0.1-alpha
         *
         */
        function render_field( $field ) { ?>
            <input type="text" value="<?php echo esc_attr( $field[ 'value' ] ); ?>" id="<?php echo esc_attr( $field[ 'id' ] ); ?>" name="<?php echo esc_attr( $field[ 'name' ] ); ?>" class="rhicomoon-select-field <?php echo esc_attr( $field[ 'class' ] ); ?>" data-json-url="<?php echo esc_attr( $field[ 'json_url' ] ); ?>"/>
        <?php }

        /**
         * input_admin_enqueue_script
         *
         * @since 0.0.1-alpha
         */
        function input_admin_enqueue_scripts() {
            # vars
            $url     = $this->settings[ 'url' ];
            $version = $this->settings[ 'version' ];

            # filters
            $icoMoonJsonFile = apply_filters( 'rhicomoon_json_url', '' );
            $url             = apply_filters( 'rhicomoon_assets_url', $url );

            # register and include CSS
            wp_register_style( 'rhicomoon-css', $url . 'assets/dist/css/style.css', [ 'acf-input' ], $version );
            wp_enqueue_style( 'rhicomoon-css' );

            # register and include JS
            wp_register_script( 'rhicomoon-js', $url . 'assets/dist/js/bundle.min.js', [ 'jquery', 'acf-input' ], $version );
            wp_enqueue_script( 'rhicomoon-js' );


            wp_localize_script( 'rhicomoon-js', 'rhicomoon', [
                'icoMoonJsonFile' => $icoMoonJsonFile
            ] );
        }
    }

    # call class
    new acf_field_icomoon_select( $this->settings );
endif;